version: '3.8'

services:
  ethereum-node1:
    image: ethereum/client-go:stable
    command: >
      --dev
      --networkid 12345
      --datadir /root/.ethereum
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api personal,eth,net,web3
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api personal,eth,net,web3
      --port 30303
      --ipcdisable
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./Data/node1:/root/.ethereum

  ethereum-node2:
    image: ethereum/client-go:stable
    command: >
      --dev
      --networkid 12345
      --datadir /root/.ethereum
      --http
      --http.addr 0.0.0.0
      --http.port 8547
      --http.api personal,eth,net,web3
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8548
      --ws.api personal,eth,net,web3
      --port 30304
      --ipcdisable
    ports:
      - "8547:8547"
      - "8548:8548"
      - "30304:30304"
    volumes:
      - ./Data/node2:/root/.ethereum

  ethereum-node3:
    image: ethereum/client-go:stable
    command: >
      --dev
      --networkid 12345
      --datadir /root/.ethereum
      --http
      --http.addr 0.0.0.0
      --http.port 8549
      --http.api personal,eth,net,web3
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8550
      --ws.api personal,eth,net,web3
      --port 30305
      --ipcdisable
    ports:
      - "8549:8549"
      - "8550:8550"
      - "30305:30305"
    volumes:
      - ./Data/node3:/root/.ethereum
