name: Python Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Src/requirements.txt

      # Step 4: Set PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/Src" >> $GITHUB_ENV

      # Step 5: Debug PYTHONPATH
      - name: Debug PYTHONPATH
        run: echo $PYTHONPATH

      # Step 6: Run all tests with coverage
      - name: Run Tests with Coverage
        run: |
          pytest --cov=Src --cov-report=xml --cov-report=term-missing --cov-fail-under=80 ./Testing/Unit

      # Step 7: Upload coverage report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      # Step 8: Start API for load testing
      - name: Start API
        run: |
          nohup uvicorn Src/API.api:app --host 0.0.0.0 --port 8000 --reload &

      # Step 9: Run Locust load tests
      - name: Run Locust Load Test
        run: |
          sleep 5  # Give API time to start
          locust -f Testing/API/locustfile.py --headless --host=http://127.0.0.1:8000 -u 10 -r 2 --run-time 5m --loglevel WARNING > Testing/API/locust_output.log 2>&1
        timeout-minutes: 10

      # Step 10: Upload Locust Logs
      - name: Upload Locust Logs
        uses: actions/upload-artifact@v3
        with:
          name: locust-logs
          path: Testing/API/locust_output.log